app:
  name: "aloh-networking"
  version: "1.0.0"
  env: "local"
  receiveSDPSize: 100
  sendSDPSize: 100

signaling:
  address: "${SIGNALING_ADDRESS}"
  port: "${SIGNALING_PORT}"
  handshakeTimeout: 10s
  idleTimeout: 10m
  keepAlivePeriodTimeout: 10s
  closeTimeout: 10s
  startTimeout: 10s
  nextProtos: ["aloh-proto"]
  maxIncomingStreams: 100
  regTimeout: 10s

networking:
  handshakeTimeout: 10s
  idleTimeout: 10m
  keepAlivePeriodTimeout: 10s
  nextProtos: ["aloh-networking"]
  stunHost: "${STUN_HOST}"
  stunPort: "${STUN_PORT}"
  turnHost: "${TURN_HOST}"
  turnPort: "${TURN_PORT}"
  turnUsername: "${TURN_USERNAME}"
  turnPassword: "${TURN_PASSWORD}"
  newSDPTimeout: 2s
  sendInStreamTimeout: 5s

handler:
  sendChatTimeout: 10s
  sendVideoTimeout: 10s
  sendVoiceTimeout: 10s
  connectTimeout: 10s
  fetchOnlineTimeout: 10s