stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - docker build -t aloh-networking-image .

test-job:
  stage: test
  script:
    - echo "testing..."
    - sleep 10s

deploy-job:
  stage: deploy 
  script:
    - cp $ENV_FILE .env
    - docker-compose down --remove-orphans
    - docker-compose up -d --build user-000
    - sleep 5
    - docker-compose logs user-000