stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - docker build -t aloh-networking-image .

test-job:
  stage: test
  script:
    - echo "testing..."
    - sleep 10s

deploy-job:
  stage: deploy 
  script:
    - cp $ENV_FILE .env
    - docker-compose rm -s user-000 || true
    - docker-compose -f docker-compose.yaml up -d --force-recreate aloh-networking-clients
    - sleep 5
    - docker-compose logs user-000