services:
  networking-bot-111:
    image: aloh-networking-image
    container_name: networking-bot-111
    command: ["-id=111"]
    stdin_open: true
    tty: true
  networking-bot-222:
    image: aloh-networking-image
    container_name: networking-bot-222
    command: ["-id=222"]
    stdin_open: true
    tty: true
  networking-bot-333:
    image: aloh-networking-image
    container_name: networking-bot-333
    command: ["-id=333"]
    stdin_open: true
    tty: true