/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#include <stdlib.h>
#include <stdint.h>

typedef const char cchar_t;

typedef uintptr_t handler;

typedef void (*DataCallback)(const char* id, void* data, size_t len);

static void call_callback(DataCallback f, const char* id, void* data, size_t len) {
    if (f) {
        f(id, data, len);
    }
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern __declspec(dllexport) handler NewHandler(cchar_t* userID, cchar_t* configPath, cchar_t* configName);
extern __declspec(dllexport) void DeleteHandler(handler h);
extern __declspec(dllexport) unsigned int Connect(handler h, cchar_t* idsStr);
extern __declspec(dllexport) unsigned int Disconnect(handler h);
extern __declspec(dllexport) unsigned int SendMessage(handler h, cchar_t* msg);
extern __declspec(dllexport) unsigned int SendVoice(handler h, void* data, int length);
extern __declspec(dllexport) unsigned int SendVideo(handler h, void* data, int length);
extern __declspec(dllexport) void RegisterOnChat(handler h, DataCallback cb);
extern __declspec(dllexport) void RegisterOnVoice(handler h, DataCallback cb);
extern __declspec(dllexport) void RegisterOnVideo(handler h, DataCallback cb);

/* Return type for FetchOnline */
struct FetchOnline_return {
	char** r0;
	int r1;
	unsigned int r2;
};
extern __declspec(dllexport) struct FetchOnline_return FetchOnline(handler h);

/* Return type for FetchSessions */
struct FetchSessions_return {
	char** r0;
	int r1;
	unsigned int r2;
};
extern __declspec(dllexport) struct FetchSessions_return FetchSessions(handler h, cchar_t* id);

#ifdef __cplusplus
}
#endif
